### ISSUE TITLE
Any Example Project to Execute

### ISSUE THREAD

**Issue by chuongmep** [dosymep/RevitCoreConsole#1]
Hi @dosymep , do we have any example project bundle like design automation to execute ? this project is interesting.

**Comment by dosymep** [comment]
Hey, you need to update your addin by this [tutorial](https://aps.autodesk.com/en/docs/design-automation/v3/tutorials/revit/step1-convert-addin/).
Than start application `RevitCoreConsole.exe forge /l ENU /i "model_path" /al "bundle_zip_path"`

My project have [examples](https://github.com/dosymep/RevitCoreConsole/tree/master/RevitCoreDBApplications), but they starts with this command `RevitCoreConsole.exe revit /i ENU /i "model_path" /fullClassName RevitDBCommand /assemblyPath "assembly_path" /journalData "[]"`

Sample
<video src='https://github.com/dosymep/RevitCoreConsole/assets/5417225/4ff9320a-fde7-4433-b2a6-960ade9f7160' width=180/>

**Comment by chuongmep** [comment]
Thank you for your help @dosymep  !
Do we need setup something for engine ? I got issue : `Autodesk.Revit.Exceptions.ArgumentException: Invalid ClientApplicationId!`, do we have any way to can work with local personal computer without server. ?
```
RevitCoreConsole.exe revit /l ENU /i "C:\Users\chuongho\OneDrive\Documents\Autodesk_Platform-Services\Tasks\MetadataExtract\MyHouseRCP_2024.rvt" /fullClassName RevitCoreDBApplications.ExportCsvCommand /assemblyPath "C:\Users\chuongho\Downloads\github\RevitCoreConsole\RevitCoreDBApplications\bin\x64\Release\2024\net48\RevitCoreDBApplications.dll" /journalData "[]"
```

**Comment by dosymep** [comment]
@chuongmep, look app config. I'm sorry, I can't say more 😏

**Comment by chuongmep** [comment]
Thank you, I will research by my self

**Comment by efdiloreto** [comment]
> Thank you, I will research by my self

Any success?

**Comment by chuongmep** [comment]
@efdiloreto  I'm sorry, I can't say more
